# 1. Importing the Libraries 

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import time


# 2. Initial Conditions

In [29]:
m1 = 1
m2 = 1
m3 = 1

#positions
initial_pos_1 = [1.0,0.0,1.0]
initial_pos_2 = [1.0,1.0,0.0]
initial_pos_3 = [0.0,1.0,1.0]

#velocity
initial_velocity_1 = [0.0,0.0,-1.0]
initial_velocity_2 = [0.0,0.0,1.0]
initial_velocity_3 = [0.0,0.0,-0.6]

initial_cond = np.array([
    initial_pos_1,initial_pos_2,initial_pos_3,
    initial_velocity_1,initial_velocity_2,initial_velocity_3
]).ravel() #2D mathi 1D ma convert kri dye, bcz y0 vadi arg ma 1D array j hovo joye

# print(initial_cond).ravel()

# 3. Define system of first order ODEs

In [25]:
def system_odes(t,sol, m1, m2, m3):
    # print(sol)
    
    p1,p2,p3 = sol[0:3], sol[3:6], sol[6:9]
    dp1_dt, dp2_dt, dp3_dt = sol[9:12], sol[12:15], sol[15:18]
    
    f1,f2,f3 = dp1_dt, dp2_dt, dp3_dt
    
    df1_dt = m2*(p2-p1)/np.linalg.norm(p2-p1)**3 + m3*(p3-p1)/np.linalg.norm(p3-p1)**3
    df2_dt = m3*(p3-p2)/np.linalg.norm(p3-p2)**3 + m1*(p1-p2)/np.linalg.norm(p1-p2)**3
    df3_dt = m1*(p1-p3)/np.linalg.norm(p1-p3)**3 + m2*(p2-p3)/np.linalg.norm(p2-p3)**3
    
    return np.array([f1,f2,f3,df1_dt,df2_dt,df3_dt]).ravel()

# 4. Solve numeric

In [30]:
time_s , time_e = 0, 10
t_points = np.linspace(time_s, time_e, 1001)

solution = solve_ivp(fun=system_odes, t_span=(time_s,time_e), y0=initial_cond, t_eval=t_points, args=(m1, m2, m3))

solution

  message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  1.000e-02 ...  9.990e+00  1.000e+01]
        y: [[ 1.000e+00  1.000e+00 ... -7.515e-01 -7.518e-01]
            [ 0.000e+00  3.553e-05 ... -1.174e+00 -1.173e+00]
            ...
            [ 0.000e+00 -3.536e-03 ...  1.915e-02  1.733e-02]
            [-6.000e-01 -6.036e-01 ... -1.362e-01 -1.326e-01]]
      sol: None
 t_events: None
 y_events: None
     nfev: 362
     njev: 0
      nlu: 0